instance_groups:
  - name: jumpbox
    jobs:
    - name: jumpbox
      properties:
        jumpbox:
          hostname: ((hostname))
          host:
            name: ((host.name))

bosh-variables:
  hostname: (( vault meta.vault "/host:name" ))
  host:
    name: (( vault meta.vault "/host:name" ))
