---
instance_groups:
- name: jumpbox
  jobs:
  - name: jumpbox
    properties:
      ssh:
        public_key: ((ssh.public_key))
        private_key: ((ssh.private_key))
        public_key_fingerprint: ((ssh.public_key_fingerprint))
      rsa:
        public_key: ((rsa.public_key))
        private_key: ((rsa.private_key))
      password: ((password))
      ca_certificate:
        ca: ((ca_certificate.ca))
        certificate: ((ca_certificate.certificate))
        private_key: ((ca_certificate.private_key))
      certificate:
        ca: ((certificate.ca))
        certificate: ((certificate.certificate))
        private_key: ((certificate.private_key))

variables:
- name: ssh
  type: ssh
- name: rsa
  type: rsa
- name: password
  type: password
- name: ca_certificate
  type: certificate
  options:
    is_ca: true
    common_name: default-ca
- name: certificate
  type: certificate
  options:
    ca: ca_certificate
    common_name: certificate.example.com
    extended_key_usage:
    - server_auth
