---
meta:
  default:
    azs: [z1]

params:
  hostname: (( concat genesis.env "-jumpbox" ))
  banner: ~
  hosts: []
  env_vars: {}
  bashrc: ~
  users: (( param "Set up some users to log into this jumpbox" ))
  ca_validity_period: 1y
  cert_validity_period: 180d

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

instance_groups:
  - name: jumpbox
    instances: 1
    azs: (( grab params.availability_zones || meta.default.azs ))
    persistent_disk_type: (( grab params.jumpbox_disk_pool || "jumpbox" ))
    vm_type:              (( grab params.jumpbox_vm_type   || "jumpbox" ))
    stemcell: default
    networks:
      - name: (( grab params.jumpbox_network || "jumpbox"))
        static_ips: (( static_ips 0 ))
    jobs:
      - name: jumpbox
        release: jumpbox
        properties:
          jumpbox:
            hostname: (( grab params.hostname ))
            users: (( grab params.users ))
            env:
              TMPDIR: /var/vcap/data/root_tmp
              .: (( inject params.env_vars ))

      - { release: jumpbox, name: inventory       }
      - { release: toolbelt, name: toolbelt       }
      - { release: toolbelt, name: toolbelt-quick }


stemcells:
  - alias: default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
- name:    jumpbox
  version: 4.7.5
  url:     (( concat "https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v" releases.jumpbox.version "/jumpbox-" releases.jumpbox.version ".tgz" ))
  sha1:    0f8a76ea4bc731e0c397da0773aa87475ce9f1b2
- name:    toolbelt
  version: 3.5.0
  url:     (( concat "https://github.com/cloudfoundry-community/toolbelt-boshrelease/releases/download/v" releases.toolbelt.version "/toolbelt-" releases.toolbelt.version ".tgz" ))
  sha1:    08b493f205680323a005ab202e0add186137cec6
